# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.13
minimum_pre_commit_version: 3.6.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - sqlmodel
  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.29.1
    hooks:
      - id: basedpyright
