services:
  app:
    build:
      context: .
      target: dev
    command: dev
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
  db:
    image: postgres:17.2-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-chatbot}
      POSTGRES_USER: ${DB_USER:-chatbot}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-chatbot}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  database:
